### ISSUE TITLE
cli: dap-collect sub command missing?

### ISSUE THREAD

**Issue by philips** [divviup/divviup-api#1076]
The dap-collect code for the cli was merged (https://github.com/divviup/divviup-api/pull/1019) but not hooked up.

Are you working on that @tgeoghegan ?

```
$ ../target/debug/divviup
error: 'divviup' requires a subcommand but one was not provided
  [subcommands: account, api-token, task, dap-client, aggregator, membership, collector-credential, help]

Usage: divviup [OPTIONS] --token <TOKEN> <COMMAND>

For more information, try '--help'.

$ ../target/debug/divviup dap-collect
error: unrecognized subcommand 'dap-collect'

  tip: a similar subcommand exists: 'dap-client'

Usage: divviup [OPTIONS] --token <TOKEN> <COMMAND>

For more information, try '--help'.
```

**Comment by tgeoghegan** [comment]
It's there, under `divviup dap-client collect [--help]`. I double checked that `cli/README.md` has the correct subcommand.

The change you started on in #1019 added `divviup dap-client upload` so it seemed natural for `collect` to be added there. It's not too late to change the layout of subcommands, of course.

**Comment by philips** [comment]
Ah ok. That is fine. Thanks!
