### ISSUE TITLE
First impressions as a user

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-api#117]
I took some notes on hiccups and surprises going through the task creation workflow for the first time. Some of these are likely known issues, and we know the form isn't complete enough for 'bring-your-own-aggregator' use cases yet, but I thought I'd record these while they're fresh.

- [ ] The file upload label, "DAP-encoded HPKE file" doesn't mention "collector". Ultimately, I'm not sure if this is a positive or negative -- it is the only HPKE keypair our users will interact with directly, after all.
- [x] #118
- [x] #119
- [x] #120
- [x] #121
- [x] #122
- [ ] The partner URL does not show up in the task creation form. (This will only be needed for the advanced bring-your-own-aggregator form)

**Comment by jbr** [comment]
This is very useful! I'm going to convert this to a bunch of issues

**Comment by jbr** [comment]
Some of them still feel unspecified — are we supporting BYOA through the web interface or just through the API? Is partner url a free-form url entry for non-BYOA? I assume we will have a preset list of partners for the standard use case, but I don't know what that interface should look like until we have the list.

**Comment by jbr** [comment]
I think this issue can now be closed — the last checkbox has been resolved by the aggregator proposal, and it's unclear to me if the HPKE Config /should/ be labeled differently. Please reopen if there's more to do here
