### ISSUE TITLE
The spinner that appears after selecting "Fixed Size" is not labeled.

### ISSUE THREAD

**Issue by jbr** [divviup/divviup-api#118]

**Comment by jbr** [comment]
@divergentdave what _should_ it be labeled?

**Comment by divergentdave** [comment]
"Maximum Batch Size" would be good. Ordering the different form controls in an intuitive way will be tricky. Naturally, minimum batch size and maximum batch size are closely related choices, but the presence/absence of it is determined by the query type. Maybe the query type should be just before minimum batch size, then the maximum batch size appears or disappears immediately after (below/to the right) the minimum batch size control?
