### ISSUE TITLE
Is dropdown for `Maximum Sum Value` the right interface?

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#147]
I'm not sure if a dropdown is the best interface for this field. It gets into exceedingly large numbers, at a certain point they start to lose any meaning.

Perhaps also the field name is misleading? On first impression, I'm left wondering why my max values are gated by powers of two, then I read the spec to understand that the max is in fact gated by the number of bits in the input.

Open to discussion on it--I'm vaguely thinking that it would be wise to have a dropdown with label `Input Size` with entries of `1..64 bits`. It's also very possible that my understanding of what this field indicates is very wrong!

![image](https://github.com/divviup/divviup-api/assets/57697428/6851d162-c11d-42f2-82f6-86b51f78546a)

**Comment by jbr** [comment]
I agree this is probably the wrong interface *or* the wrong options. In particular, I have trouble imagining how someone could decide between any of the larger sizes.

We could potentially allow them to free-form enter the maximum number they want to support, and then we show them the next power of two. Or we could reduce the options and present a handful of maxima in the interface and they can always use the api directly if they have a use case we haven't thought of
