### ISSUE TITLE
Task detailed view not giving complete information.

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#150]
I _think_ the tasks view isn't giving me all the info I need to configure a DAP client. Referring to https://www.ietf.org/archive/id/draft-ietf-ppm-dap-04.html#section-4.2 or https://github.com/divviup/janus/blob/main/client/src/lib.rs#L60 -- in particular it looks like I'm missing the Task ID.

![image](https://github.com/divviup/divviup-api/assets/57697428/38daf55e-a0a8-40f3-a701-f6eab0732917)

**Comment by jbr** [comment]
I believe this is a duplicate of #121 👍

**Comment by inahga** [comment]
True!
