### ISSUE TITLE
Logo on Auth0 screen is disproportionately small.

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#152]
Minor bug: The Divvi Up logo on the Auth0 screen is disproportionately small. ![image](https://github.com/divviup/divviup-api/assets/57697428/9c05afaf-4329-4908-8b96-e47a027e2ff5)

Using Firefox 113 on Linux (amd64). Display is 3840x2160 at 100% scaling, zoom is at 150% (icon scales with zoom).

**Comment by jbr** [comment]
Options:
1. <img width="747" alt="image" src="https://github.com/divviup/divviup-api/assets/13301/d464b7f9-0389-447a-af3b-ae04eba610ff">
2. <img width="744" alt="image" src="https://github.com/divviup/divviup-api/assets/13301/72190970-4eb2-4924-bbad-7feee28e2ae8">

**Comment by jbr** [comment]
Went with this. Closing for now, but I imagine we'll revisit this 
<img width="1552" alt="image" src="https://github.com/divviup/divviup-api/assets/13301/ec434687-4077-4a37-b2bc-af955cc6ca9c">
