### ISSUE TITLE
Multi-factor authentication for new accounts should be optional

### ISSUE THREAD

**Issue by branlwyd** [divviup/divviup-api#153]
When I created my account in the staging environment, I was forced to set up multi-factor authentication (MFA), e.g. a TOTP or WebAuthn device. IMO, new users should have the option to skip MFA, leaving their account protected by username/password only.

**Comment by jbr** [comment]
This was a misunderstanding — I thought we wanted to *require* it. Updated [here](https://manage.auth0.com/dashboard/us/dev-phobte3gvtui5fig/security/mfa)

**Comment by branlwyd** [comment]
I may have forgotten context in the original discussion, but I think I was interpreting "MFA is required" in the sense of "allowing users to use MFA is a product requirement" as opposed to "requiring users to use MFA". (If this doesn't match others' expectations, please poke this bug & we'll discuss.)
