### ISSUE TITLE
Background task to prune expired sessions from the database

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-api#154]
In staging, we currently have about three weeks worth of session rows in the database. The trillium-sessions documentation says that it is the application's responsibility to perform cleanup of expired sessions. We should either do so as part of a repeating background task, or write a separate entry point for session cleanup, and invoke that from a CronJob.

**Comment by jbr** [comment]
Thinking a bit about this, we also will need to clean up the queue at some point.

I think it would be convenient to use the queue for scheduled jobs, as we'd get visibility and any improvements to the queue tooling will advantage both on-demand and scheduled uses.

Looking at other queue schedulers, it seems like people usually have one process that's always responsible for enqueuing scheduled tasks, even if it gets picked up by another task. Assuming we're horizontally scaling this service, we'll need a way of appointing one of them the leader with a config variable
