### ISSUE TITLE
Cannot delete membership of partially set-up user

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-api#191]
I tried deleting a user membership in an account for someone whose "invitation" password reset email had expired, with the intention of re-adding them to trigger another email. (though I'm not sure whether that will work) When I clicked on the "Remove" confirmation button, nothing happened, and I saw that a DELETE request in the network monitor returned a 404 status.

**Comment by jbr** [comment]
If you reload the page, my hunch is that the membership was deleted and then a subsequent delete 404ed

**Comment by divergentdave** [comment]
No, I tried reloading the page and the member was still there. This is likely a separate issue particular to outstanding invitations.

**Comment by jbr** [comment]
I can't think of why that would be a distinct state to the service unless a queue job is currently locking the membership

**Comment by divergentdave** [comment]
I peeked at the database and that explained it. The membership had been deleted, but the `GET https://api.staging.divviup.org/api/accounts/.../memberships` request is being cached too aggressively by Firefox. The network monitor always shows it is "cached". Hitting control-shift-R doesn't affect it, obviously because it's triggered by XHR/fetch rather than a subresource. Fiddling with the request to add a query parameter and resend it confirms that the membership no longer shows up when a request is actually made.
