### ISSUE TITLE
Aggregator entity: API

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-api#197]
To support BYOHelper, the `divviup-api` API needs endpoints for CR~U~D on aggregators.

###### `POST /accounts/:account_id/aggregators`

Creates a new aggregator in an account. The request must be authenticated with a valid token for `:account_id`. The body is a JSON object containing:

- The display name for the aggregator,
- The aggregator API URL;
- A bearer token for authenticating requests to the aggregator API;
- The DAP API URL.

If the request is valid, `divviup-api` adds a row to its aggregators table for the new aggregator, marking it as belonging to `:account_id`. On success, the response is 201 Created. The response body is a JSON object containing the aggregator ID. Subsequently, requests to `POST /accounts/:account_id/tasks` may reference the aggregator ID.

###### `POST /aggregators`

Creates a new global aggregator, usable by any account. Only `divviup-api` administrator users may use this API. The request and responses are identical to `POST /accounts/:account_id/aggregators`. n.b.: this interaction is not illustrated in any sequence diagram.

###### `GET /accounts/:account_id/aggregators`

Lists all the aggregators that this account may use in tasks, including the global aggregators. The request must be authenticated with a valid token for `:account_id`. The response is 200 OK and the body is a list of JSON objects containing:

- Aggregator ID;
- Aggregator API URL;
- Bearer token for authenticating to the aggregator API;
- DAP API URL;
- Boolean indicating whether the aggregator is global.
- Aggregator display name.

_Open question_: Would a client ever want to get a list of just the account-specific aggregators, or just the global ones? If so, then we need a separate `GET /aggregators`, but I think the combined list will always be short enough that it's OK to return them all and make the client filter on the `global` boolean.

###### `GET /aggregators/:aggregator_id`

Queries for an existing aggregator's information. The response is 200 OK and the body is a JSON object containing a single object of the same format as that returned from `GET /accounts/:account_id/aggregators`.

###### `DELETE /aggregators/:aggregator_id`

Deactivates an aggregator. There is no request body. The response is 204 No Content. To delete an aggregator associated with an account, the client must present a valid token for that account. Only `divviup-api` administrators may delete a global aggregator.

Deactivating an aggregator means that no new tasks may be created referencing the aggregator. However any existing tasks using that aggregator may continue to run until they expire.

**Comment by jbr** [comment]
Other entities with human-readable names like Tasks and Accounts have `PATCH` routes that currently exclusively allow modifying the name. Proposal: Add a similar `PATCH /aggregators/:aggregator_api` for consistency and because it seems inevitable people will want to rename their aggregators, even if only because they tombstoned their old "MyCompany Aggregator" and want to rename it to "MyCompany Aggregator (old)" or similar
