### ISSUE TITLE
Task creation API endpoint should take references to paired helpers

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-api#199]
The `POST /accounts/:account_id/tasks` needs to allow specifying an aggregator ID instead of `partner_url`, allowing `divviup-api` to look up the information of a previously paired aggregator. The handler also needs to reach out to the aggregator's aggregator API to provision the task in it. We will have to revisit the [NewTask](https://github.com/divviup/divviup-api/blob/f1d268f9881b9b0dcb966de746c6e379a19dd59c/src/entity/task/new_task.rs#L15) message definition to remove the fields for (task) `id`, `vdaf_verify_key`, `aggregator_auth_token` and `collector_auth_token`, since those will be generated by `divviup-api` rather than chosen by the subscriber.

**Comment by divergentdave** [comment]
I think we may want to leave the `id`, `vdaf_verify_key`, `aggregator_auth_token`, and `collector_auth_token` fields for now, and just validate that they are not present when an aggregator ID is, or when the referenced aggregator has an aggregator API endpoint configured. For BYOHelper use cases without automated task provisioning, subscribers may want to provide these manually, and in fact this is what our `in_cluster` integration test currently does.

**Comment by jbr** [comment]
> I think we may want to leave the `id`, `vdaf_verify_key`, `aggregator_auth_token`, and `collector_auth_token` fields for now, and just validate that they are not present when an aggregator ID is, or when the referenced aggregator has an aggregator API endpoint configured. For BYOHelper use cases without automated task provisioning, subscribers may want to provide these manually, and in fact this is what our `in_cluster` integration test currently does.

In order to address this "externally-provisioned aggregator" configuration, I'm going to add a flag to the Aggregator that indicates that it is externally provisioned, but still require exactly two Aggregators per Task. `id`, `vdaf_verify_key`, `aggregator_auth_token` and `collector_auth_token` will be accepted if and only if one (or both, hypothetically?) of the aggregators is configured to not provision.
