### ISSUE TITLE
add interface for aggregators

### ISSUE THREAD

**Issue by jbr** [divviup/divviup-api#214]
- [x] list account aggregators
- [x] create new account aggregator
- [x] edit name of account aggregator
- [x] tombstone / delete account aggregator
- [x] admins: list shared aggregators
- [x] [admins: tombstone / delete shared aggregators](https://github.com/divviup/divviup-api/issues/334)
- [ ] [admins: edit shared aggregator name](https://github.com/divviup/divviup-api/issues/335)
- [x] admins: create shared aggregators

**Comment by divergentdave** [comment]
When looking at an account-level aggregator, there should be a button to tombstone/delete it. I don't see this in the interface as of 0.0.15.

**Comment by jbr** [comment]
Yeah, those are the two remaining checkboxes on this list. Should be quick
