### ISSUE TITLE
Bug: Error when logging into staging

### ISSUE THREAD

**Issue by TanviHacks** [divviup/divviup-api#283]
Upon login, I see the following on the site:
expected pkce verifier in session

Hitting the back button, I'm able to get back to my account.

Unfortunately, I have not been able to reproduce a second time.

**Comment by jbr** [comment]
@TanviHacks How did you arrive at the login page initially? Is it possible that an auth0 login page was open for a very long time?

**Comment by TanviHacks** [comment]
> @TanviHacks How did you arrive at the login page initially? Is it possible that an auth0 login page was open for a very long time?

Yes actually that is possible.
