### ISSUE TITLE
Menu for Home and Accounts redundant

### ISSUE THREAD

**Issue by TanviHacks** [divviup/divviup-api#318]
When you are on the Home / Accounts page, clicking the blue Home link doesn't do anything since Home and Home / Accounts are both at https://app.staging.divviup.org/accounts.  Here are a few potential options, some of which we have briefly discussed:
* We could remove the href on Home
* Create https://app.staging.divviup.org/home as a welcome/intro page.  Clicking on both home or the Divviup logo on the top left would take you there.
* Create a left hamburger menu that can take a user to the different sections of each Account.

**Comment by jbr** [comment]
I think a good first step would be removing `Home`, as that page no longer exists
