### ISSUE TITLE
Allow subscribers to use a single collector auth token across several tasks

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-api#455]
Currently, when a task is provisioned via `divviup-api` and the Janus aggregator API, the leader will always [generate a new collector authentication token](https://github.com/divviup/janus/blob/5294b7d4800acaad1cbd5792e5fb5594aac4f4d4/aggregator_api/src/routes.rs#L131). That means that subscribers have to securely store and manage one collector auth token for each task they provision into Divvi Up. Contrarily, we allow subscribers to manage an HPKE configuration as a resource in `divviup-api` and then re-use that across multiple tasks. It'd be nice if collector auth tokens had the same cardinality as HPKE configurations.

We could achieve this by extending `divviup-api`'s existing `hpke_configs` resource into something like "collector credentials", which would encompass both an HPKE configuration and a bearer token for authenticating requests to the DAP collection API. Subscribers are currently responsible for generating HPKE private keys, so similarly we can have them generate the auth token.

**Comment by tgeoghegan** [comment]
reserved for timg to draft a solution outline!

**Comment by jbr** [comment]
What's the case to be made for backwards compatibility at this stage? Who are the users that would be distrusted by the elimination of the current hpke_config endpoints?

**Comment by tgeoghegan** [comment]
I was thinking that some subscribers might be happy to use a different collector auth token for each task, but now I realize they could achieve that themselves by creating a new `collector_credential` every time they provision a task.

**Comment by jbr** [comment]
Or we could have that be a nullable property and if it's null, we'll randomly generate a collector token for each task

**Comment by jbr** [comment]
Does this proposal also remove the `GET /api/tasks/:task_id/collector_auth_tokens` endpoint?

**Comment by tgeoghegan** [comment]
> Does this proposal also remove the `GET /api/tasks/:task_id/collector_auth_tokens` endpoint?

I can go either way on this. If the subscriber is responsible for generating the tokens, then we don't _need_ to expose it, but we could still implement it since Janus will still need to store the token (at least until we take that change for Janus to store token hashes), and it's a nice safety net in case the subscriber loses their token.

Also, it depends on whether we want to continue supporting generating auth tokens for subscriber or not. If we do, then I think we need that endpoint.

**Comment by jbr** [comment]
> Also, it depends on whether we want to continue supporting generating auth tokens for subscriber or not. If we do, then I think we need that endpoint.

I agree on this count.

> it's a nice safety net in case the subscriber loses their token.

But not on this one. If the token is bundled with the private key and they lose that bundle, it doesn't really help much for us to echo the token back

**Comment by tgeoghegan** [comment]
Yeah, you're absolutely right -- we don't intend to start escrowing HPKE private keys, so we should aim to get out of the business of escrowing auth tokens, too.

**Comment by jbr** [comment]
The only circumstance in which we'd want to hang onto a private key is if we're acting as the collector at some point in the future, but at that point we still never need to reveal it. So I think the only situation in which we'd need the tasks/:task_id/collector_auth_tokens endpoint is if we continue supporting per-task randomly generated tokens.

**Comment by jbr** [comment]
I believe this is done?
