### ISSUE TITLE
Allow Collector to discover tasks

### ISSUE THREAD

**Issue by branlwyd** [divviup/divviup-api#488]
To simplify Collector implementation, we should provide some (extra-DAP) way for the Collector to discover tasks. This would simplify Collector configuration.

* Collectors will probably want some ability to filter tasks, to allow different tasks to be collected by different Collector deployments.
  * One way to do this would be by collector credential. This would work great as long as folks configuring the Collectors don't use the same Collector credentials across different Collector deployments.
  * We can choose to let Collectors do this filtering themselves.
* Ideally this would be usable by non-DU-authored Collectors.

**Comment by jbr** [comment]
related to #486

**Comment by branlwyd** [comment]
Closing as dupe of #486.
