### ISSUE TITLE
Should we truncate Prio3 from VDAF names?

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#490]
Slight nit: In the UI we truncate e.g. `Prio3Sum` to `sum`. Should we keep the Prio3 part? All our client libraries currently address VDAFs by their full name, so truncating them in the UI might lead to confusion.

**Comment by jbr** [comment]
I don't think end users should ever have to think about "prio3" — that's an implementation detail of what they're trying to accomplish, which is an operation like sum/count/histogram. The interface to use a particular vdaf doesn't need to contain the fully qualified name of the vdaf as it's represented in the spec

**Comment by inahga** [comment]
My thought is the end-user is also someone who likely will also implement functionality in a client. Our client libraries leak the Prio3 name, so they do have to think about it anyways. (e.g. [TS](https://divviup.github.io/divviup-ts/modules/_divviup_prio3.html), [Rust](https://docs.rs/prio/0.12.2/prio/vdaf/prio3/index.html))

I think this is nit-y enough of me that we can just leave it for if we get subscriber feedback.

**Comment by jbr** [comment]
The top level `@divviup/dap` ts client also uses "sum"/"count"/"histogram" ¯\_(ツ)_/¯
