### ISSUE TITLE
Add workflows to publish divviup-cli and divviup-client to crates.io

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#493]
So that subscribers can `cargo install divviup-cli` without the `--git` argument.

**Comment by jbr** [comment]
I updated the title because this is more of a "set up a reusable workflow" than a one off "publish from local machine"

**Comment by tgeoghegan** [comment]
This is done by #783, right? AFAICT the new workflow creates a release, which will trigger `.github/workflows/publish-crates.yml`. @inahga would you please close this unless there's something else you want to do here?

**Comment by inahga** [comment]
Moreso accomplished by @jbr in https://github.com/divviup/divviup-api/pull/595, but yes in any case. I can `cargo install divviup-cli` just fine now.
