### ISSUE TITLE
Aggregator-api collector auth token hash changes

### ISSUE THREAD

**Issue by jbr** [divviup/divviup-api#542]
Alongside DAP-07, Janus leaders will be accepting hashed collector auth tokens instead of a raw token. In order to accommodate this,

* [x] #560
* [x] #562
* [x] #564
* [ ] #570
* [x] #566
* [x] #567
* [x] #568

in the above, "`+TokenHash` tasks" are defined as "tasks for which the leader has opted into the `TokenHash` feature"

**Comment by tgeoghegan** [comment]
We opted to name the feature `TokenHash` for consistency with other camel case strings in the aggregator API configuration message.
