### ISSUE TITLE
Error using divviup-api 0.0.27 with Postgres

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-api#546]
I tried going through account creation and saw the following error in the server logs.

```
[2023-10-04T00:40:34Z ERROR divviup_api::handler::error] Query Error: error returned from database: null value in column "intends_to_use_shared_aggregators" of relation "account" violates not-null constraint
"api.example" integration@test.example (admin): POST /api/accounts 1.590987ms 500
```

The migration sets a default value in the SeaQL statement adding the column. I rendered the statement using `PostgresQueryBuilder` and got the following.

```
ALTER TABLE "account" ADD COLUMN "intends_to_use_shared_aggregators" bool NOT NULL DEFAULT FALSE
```

I think the issue is that the `INSERT` statement later includes intends_to_use_shared_aggregators in the column list, and provides a null value. The column's default value only comes into play for columns not in the column list.

**Comment by jbr** [comment]
Shoot, we do in fact want it to be null

**Comment by jbr** [comment]
I'm not sure why this passed locally but it's possible I was using an older version of the migration that used a nullable Boolean before I realized we never set it to false. Is this deployed?
