### ISSUE TITLE
Click to copy buttons are not working

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-api#549]
In the account setup flow, the "click to copy" buttons (next to the API token and hpke-config generate command) are not working for me in Firefox 118. I confirmed that GitHub's "copy to clipboard" buttons are working, so it's not just a snapd issue.

**Comment by jbr** [comment]
is that also true on a task detail page for a created task and also true if you click the text instead of the button? I assume so for both of those but want to confirm before digging into a fix

**Comment by divergentdave** [comment]
It would take me a bit to stand up and pair two aggregators locally, in order to create a task, so I think I'll wait for 0.0.28 to hit staging and test there later today.

**Comment by divergentdave** [comment]
This is only an issue with non-secure domains (`http://app.example/` in this case, via /etc/hosts). MDN's implementation notes for Firefox say the feature is gated on secure contexts. I expect this should work just fine in staging/production.

**Comment by divergentdave** [comment]
I confirmed the buttons are working in staging.
