### ISSUE TITLE
Task deletion

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#862]

**Comment by tgeoghegan** [comment]
There's a few different notions of task deletion that could be useful, and involve varying degrees of implementation complexity and risk:

- Hiding tasks from the UI so they don't clutter up the task list (low risk since this wouldn't involve talking to Janus)
- Setting a tombstone all the way through the Janus DB, instructing Janus to stop accepting uploads for the task (early task expiration)
- Making Janus synchronously delete the task. Almost certainly a bad idea because that triggers expensive cascading DELETEs, but maybe we'd want this as an admin-only interface?

**Comment by inahga** [comment]
> Setting a tombstone all the way through the Janus DB, instructing Janus to stop accepting uploads for the task (early task expiration)

I think I like this idea the most.

I would approach it like so:
- Users can `Delete` or `Expire` a task.
    - `Delete` immediately removes the task from the UI and expires the task in Janus.
    - `Expire` expires the task in Janus, but leaves it in the UI (perhaps greyed out) so that the user can monitor the `Task Expired` metric, to see if any reports still come in.
    - `Expire`d tasks can be deleted to remove it from the UI.

We can let GC clean up artifacts of expired tasks as normal.

I believe task expiry can also be undone safely?

**Comment by jbr** [comment]
It sounds like we'd want a PATCH endpoint for janus to change any changeable field (which right now is just expiry?)

**Comment by inahga** [comment]
I think so. This should be a relatively straightforward to add to Janus. I can make a PR.

For thorough accounting, it would need to be run against the helper too. We don't have full control over when folks are going to update their helper to get this endpoint, so expiry might need to be done on a best-effort basis (i.e. ignore 404 errors). Or we can introduce a feature.

The problem with the current DELETE endpoint is that it will do a cascading delete of a task, which for tasks with many client uploads may not be possible in a reasonable amount of time. (Arguably we shouldn't even have it, but I think it may have reasonable use cases for local testing or operator use).

**Comment by inahga** [comment]
> Hiding tasks from the UI so they don't clutter up the task list (low risk since this wouldn't involve talking to Janus)

Alternatively we can take this approach. This will solve the immediate use case that we have without getting too complicated. Since no information is actually being deleted, we have lots of room to iterate on this.

**Comment by jbr** [comment]
I think whether we add a feature depends on whether we'd want some logic to be conditional on the anomalous state where one aggregator has the task and the other doesn't, as distinguished from "does not speak PATCH /api/tasks/:task_id" — if we want to do the same thing either way (log and ignore, I assume?) we could get away without adding a feature. If we want to blow up more spectacularly when the task only exists in one aggregator, then we'd want the feature. Does that sound right?

**Comment by inahga** [comment]
> If we want to blow up more spectacularly when the task only exists in one aggregator

I suspect if this were the case, there are other more spectacular problems (i.e. the helper underwent a DB or data loss), and we wouldn't want to necessarily block task deletion.

So SGTM, we can have the expiration accounting to Janus be best-effort and avoid a new feature.

**Comment by inahga** [comment]
Something to consider is that task expiry isn't quite immediate, due to Janus having no task cache invalidation https://github.com/divviup/janus/issues/238. Or rather, its task invalidation strategy is a restart.

This is not a blocker, it's just something to consider if we see unexpected results.
