### ISSUE TITLE
UI crash when navigating to histogram created via CLI

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#925]
Create histogram task with these args via the API/CLI:
```
          "--vdaf",
          "histogram",
          "--min-batch-size",
          "100",
          "--time-precision",
          "60s",
          "--length",
          "1024"
```

Results in a UI crash.
<img width="1732" alt="image" src="https://github.com/divviup/divviup-api/assets/57697428/fe04c555-66a3-4cd9-9939-98dd07d7eafe">

**Comment by divergentdave** [comment]
This is being tracked over at https://github.com/divviup/divviup-api/issues/438#issuecomment-1863658274

**Comment by inahga** [comment]
Oops, thanks for catching that!
